#!/bin/bash


### copy ssh-key to authorized keys in ather machine ###

read -p "Enter Source Server: " SOURSRV

read -p "Enter Source User:" SOURUSER

read -p "Enter Destination Server:" DESTSRV

read -p "Enter Destination User:" DESTUSER

##ssh root@$DESTSRV "test -e /home/$DESTUSER/.ssh/authorized_keys"
##if [ $? -eq 0 ];
## then

 ssh root@$SOURSRV cat '/home/'$SOURUSER'/.ssh/id_rsa.pub' | ssh root@$DESTSRV -T "cat >> /home/"$DESTUSER"/.ssh/authorized_keys"

## else
## echo ""
##fi
