#!/bin/bash


### copy ssh-key to authorized keys in ather machine ###

read -p "Enter Source Server: " SOURSRV

read -p "Enter Source User:" SOURUSER

read -p "Enter Destination Server:" DESTSRV

read -p "Enter Destination User:" DESTUSER


options=("One way" "Back and Forth" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "One way")
		ssh root@$SOURCE_SRV cat '/home/'$SOURCE_USER'/.ssh/id_rsa.pub' | ssh root@$DEST_SRV -T "cat >> /home/"$DEST_USER"/.ssh/authorized_keys"
                break
                ;;
        "Back and Forth")
		ssh root@$SOURCE_SRV cat '/home/'$SOURCE_USER'/.ssh/id_rsa.pub' | ssh root@$DEST_SRV -T "cat >> /home/"$DEST_USER"/.ssh/authorized_keys"
		ssh root@$DEST_SRV cat '/home/'$DEST_USER'/.ssh/id_rsa.pub' | ssh root@$SOURCE_SRV -T "cat >> /home/"$SOURCE_USER"/.ssh/authorized_keys"
                break
                ;;
        "Option 3")
            echo "you chose choice $REPLY which is $opt"
            ;;
        "Quit")
            exit
            ;;
        *) 
	   echo "invalid option $REPLY";;
    esac
done
